version: '2'
services:
  elasticsearch:
    build: es
    volumes:
        - es-data:/usr/share/elasticsearch/data
        - ./es/config:/usr/share/elasticsearch/config
    environment:
        - HTTP_PROXY=${HTTP_PROXY}
    ports:
        - 9200:9200
    expose:
        - 9300
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
        # https://github.com/docker-library/elasticsearch/issues/111
        # uliimit
  kibana:
    build: kibana
    links:
        - elasticsearch:elasticsearch
    environment:
        - HTTP_PROXY=${HTTP_PROXY}
    ports:
        - 5601:5601

volumes:
    es-data:
        driver: local
